Algoritmo "variáveis"
// 
//  
// Descrição   : Segundo algoritmo
// Autor(a)    : Thiago Assueiro
// Data atual  : 9/9/2021
Var
// Seção de Declarações das variáveis 
// Primeiro nome
// Segundo nome
// Idade
// Cidade
// Endereço

   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo