Algoritmo "Concatenação"
// 
//  
// Descrição   : Desenvolvimento
// Autor(a)    : Thiago A.
// Data atual  : 9/9/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o nome: ")
   leia(nome)
   escreval("Digite o número: ")
   leia(numero)
   
   escreval(nome, ":", numero)
   
Fimalgoritmo